language: ruby
rvm:
  - 2.4.1

before_script:
  - chmod +x _bin/html-validate.sh

script: _bin/html-validate.sh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

cache: bundler

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false