# Site settings
title: terrehbyte
logo: "/favicon/favicon-310.png"
email: terreh@terrehbyte.com
description: "Programming and game development notes written by a developer working on games in Unity3D and Unreal Engine."
baseurl: ""
url: "https://terrehbyte.com"
webmaster_realname: Terry Nguyen
twitter_username: terrehbyte
github_username:  terrehbyte
chrome_theme_color: '#0e0e0e'

authors:
  terrehbyte:
    real_name: Terry Nguyen
    display_name: terrehbyte
    twitter: terrehbyte
    github: terrehbyte
    url: "https://terrehbyte.com"

# External services

## Uncomment and supply tracking ID to use Google Analytics
ga_tracking_id: UA-55657788-1

## Uncomment and supply forum shortname to use Disqus
disqus_short_name: terrehbyte

# Build settings
safe: true

encoding: utf-8
timezone: US/Pacific

permalink: /:title/

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle

whitelist:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sass-converter
  - jekyll-textile-converter

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

# Defaults
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts
