baseURL = "/"
languageCode = "en-us"
title = "Terry Nguyen"
theme = "cactus"
copyright = "Terry Nguyen" # cactus will use title if copyright is not set
enableEmoji = true

# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-55657788-1"

[params]
  colortheme = "terry" # dark, light, white, classic, or terry (based on white)
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  logo = "images/terry_irl_tiny.jpg"
  showHeaderOnPosts = true

  # Home page settings
  description = "Terry Nguyen's Blog"

  intro = """
  **Howdy, I'm Terry (aka terrehbyte)!**

  I work as a **Game Programmer** :gear: and **Educator** :apple: but spare some
  time for tinkering with **mechanical keyboards** :keyboard: and some
  **gaming** :video_game: when I can.

  Please reach out if you've got a question or have an opportunity to discuss.
  
  ----
  """
  
  mainSection = "posts" # your main section
  noticesSection = "thirdparty" # your notices section
  mainSectionTitle = "Recent Posts" # your main section heading label
  noticesSectionTitle = "NOTICES" # your notices section label
  showAllPostsOnHomePage = false # default to false
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/terrehbyte" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default 2006-01-02

  # Post page settings
  show_updated = true # defaults to false
  showReadTime = false # default to false

  showMobileMenu = false

  #[params.comments]
   # enabled = false # default
    #engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands

  [[params.social]]
    name = "email"
    link = "terry@terrehbyte.com"  # no need for "mailto:" in the head
  [[params.social]]
    name = "github"
    link = "https://github.com/terrehbyte"
  [[params.social]]
    name = "mastodon"
    link = "https://mastodon.gamedev.place/@terrehbyte"
    rel = "me"
  [[params.social]]
    name = "mastodon"
    link = "https://sakurajima.moe/@terrehbyte"
    rel = "me"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/terrehbyte"
  [[params.social]]
    name = "discord"
    link = "/discord"
    target = "_self"
  [[params.social]]
    name = "facebook"
    link = "https://www.facebook.com/terrehbyte/"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/terrehbyte/"

[permalinks]
  posts = "/:filename/"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about-me"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4
