baseURL = "/"
languageCode = "en-us"
title = "Terry Nguyen @ terrehbyte"
theme = "cactus"
copyright = "Copyright &copy; 2012-2021 Terry Nguyen" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

[params]
  colortheme = "terry" # dark, light, white, classic, or terry (based on white)
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  logo = "images/terry_irl_tiny.jpg"

  # Home page settings
  description = "<strong>Hey, Terry here!</strong><br>You can find my blog posts, past projects, and other things about me on my website."
  
  mainSection = "posts" # your main section
  mainSectionLabel = "Recent Posts" # your main section heading label
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/terrehbyte" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default
  showReadTime = false # default

  #[params.comments]
   # enabled = false # default
    #engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/terrehbyte"
    [[params.social]]
    name = "facebook"
    link = "https://www.facebook.com/terrehbyte/"
  [[params.social]]
    name = "github"
    link = "https://github.com/terrehbyte"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/terrehbyte/"
  [[params.social]]
    name = "email"
    link = "terry@terrehbyte.com"  # no need for "mailto:" in the head

[permalinks]
  posts = "/:filename/"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Archive"
url = "/posts"
weight = 3

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 3

[[menu.main]]
name = "About"
url = "/about me"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.goldmark.renderer]
  unsafe= true