baseURL = "/"
languageCode = "en-us"
title = "Terry Nguyen"
theme = "cactus"
copyright = "Terry Nguyen" # cactus will use title if copyright is not set
enableEmoji = true

# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-55657788-1"

[params]
  colortheme = "terry" # dark, light, white, classic, or terry (based on white)
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  logo = "images/terry_irl_tiny.jpg"
  showHeaderOnPosts = true

  # Home page settings
  description = "Terry Nguyen's Blog"

  intro = """
  **Howdy, I'm Terry (aka terrehbyte)!**

  I work as a :gear: **Game Programmer** and :apple: **Educator** but spare some
  time for tinkering with :keyboard: **mechanical keyboards** and some
  :video_game: **gaming** when I can.

  Please reach out if you've got a question or have an opportunity to discuss~!
  
  ----
  """
  
  customSectionBody = """
  ## Featured Works
  {{< game-covers >}}
  """
  customSectionNavLink = "/projects/"
  customSectionNavLinkLabel = "All Works"

  mainSection = "posts" # your main section
  projSection = "/about-me/#projects" # your projects section
  noticesSection = "thirdparty" # your notices section
  mainSectionTitle = "Recent Posts" # your main section heading label
  projectsSectionTitle = "Recent Project" # your projects section heading label
  noticesSectionTitle = "NOTICES" # your notices section label
  showAllPostsOnHomePage = false # default to false
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/terrehbyte" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default 2006-01-02

  # Post page settings
  show_updated = true # defaults to false
  showReadTime = false # default to false

  showMobileMenu = false

  #[params.comments]
   # enabled = false # default
    #engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands

  [[params.social]]
    name = "email"
    friendly_name = "e-mail"
    link = "terry@terrehbyte.com"  # no need for "mailto:" in the head
    home = true
    tags = [ "contact" ]
  [[params.social]]
    name = "github"
    link = "https://github.com/terrehbyte"
    tags = [ "portfolio" ]
  [[params.social]]
    name = "mastodon"
    friendly_name = "Gamedev Mastodon"
    link = "https://mastodon.gamedev.place/@terrehbyte"
    rel = "me"
    tags = [ "social" ]
  [[params.social]]
    name = "mastodon"
    friendly_name = "Sakurajima Mastodon"
    link = "https://sakurajima.moe/@terrehbyte"
    rel = "me"
    tags = [ "social" ]
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/terrehbyte"
    tags = [ "social" ]
  [[params.social]]
    name = "discord"
    link = "/discord"
    target = "_self"
    tags = [ "social" ]
  [[params.social]]
    name = "bsky"
    link = "https://bsky.app/profile/terrehbyte.bsky.social"
    rel = "me"
    tags = [ "social" ]
  [[params.social]]
    name = "linkedin"
    friendly_name = "LinkedIn"
    link = "https://www.linkedin.com/in/terrehbyte/"
    home = true
    tags = [ "contact" ]

[permalinks]
  posts = "/:filename/"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about-me"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 4
